[wasm] Enable previously disable benchmark (#3117)
Fixes https://github.com/dotnet/performance/issues/1948 .

This was disabled 2 years ago due to a build failure:

```
error: Invalid cast (Producer: 'LLVM11.1.0' Reader: 'LLVM 13.0.0git')
```

.. which is not hit any more.