Bug fixes and updating comments. (#228)
- https://github.com/dotnet/performance/pull/218 introduced this bug:
```log
target_framework_moniker = FrameworkAction.get_target_framework_moniker(framework)
NameError: name 'FrameworkAction' is not defined
```
- Pull released `dotnet-install` script instead of latest from `dotnet/cli:master`.
- Minor fixing spacing and follow naming conventions: two lines between global functions, and camel case naming.
- Updated TODO/FIXME comments on the scripts.